apiVersion: apps/v1
kind: Deployment
metadata:
  name: american-predictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: american-predictor
  template:
    metadata:
      labels:
        app: american-predictor
    spec:
      containers:
      - name: american-predictor
        image: ziangzhou/image-proj2:latest
        ports:
        - containerPort: 5017