apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proj2-predictor
  template:
    metadata:
      labels:
        app: proj2-predictor
    spec:
      containers:
      - name: proj2-predictor
        image: ziangzhou/image-proj2:latest
        ports:
        - containerPort: 5017