apiVersion: apps/v1
kind: Deployment
metadata:
  name: zz188-proj2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zz188-proj2-predictor
  template:
    metadata:
      labels:
        app: zz188-proj2-predictor
    spec:
      containers:
      - name: zz188-proj2-predictor
        image: ziangzhou/image-proj2:0.2.2
        ports:
        - containerPort: 5017