apiVersion: v1
kind: Service
metadata:
  name: zz188-proj2-service
spec:
  selector:
    app: zz188-proj2-predictor
  ports:
    - protocol: TCP
      port: 5017
      targetPort: 5017
  type: LoadBalancer